name: flutter_phoenix
description: Easily restart your application from scratch, losing any previous state
version: 0.2.1+1
homepage: https://github.com/mobiten/flutter_phoenix
repository: https://github.com/mobiten/flutter_phoenix
issue_tracker: https://github.com/mobiten/flutter_phoenix/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.7.0

